apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightroutedisplay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flightroutedisplay
  template:
    metadata:
      labels:
        app: flightroutedisplay
    spec:
      containers:
      - name: flightroutedisplay-container
        image: disneycode/2flightroutedisplay:v1.0.0-<dynamic-tag>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
