apiVersion: v1
kind: Service
metadata:
  name: flightroutedisplay-service
spec:
  selector:
    app: flightroutedisplay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
