name: Deploy React App to S3

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Upload to S3
        run: |
          aws s3 cp ./build/ s3://dfsfsdf/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2  # Change this to your S3 bucket's region


# name: Deploy React App to S3

# on:
#   push:
#     branches:
#       - main  # Change this to your main branch name

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18   #Change this to your desired Node.js version

#       - name: Install dependencies
#         run: npm install

#       - name: Build React App
#         run: npm run build

#       - name: Deploy to S3
#         uses: jakejarvis/s3-sync-action@master
        
#         with:
#           args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: us-east-2  # Change this to your S3 bucket's region
#           # SOURCE_DIR: build


# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: your-docker-repo:latest

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Deploy to AWS Elastic Beanstalk (or other AWS service)
#         run: |
#           eb deploy FlightRouteViewer
#         env:
#           AWS_DEFAULT_REGION: us-east-1
#         secrets:
#           - AWS_ACCESS_KEY_ID
#           - AWS_SECRET_ACCESS_KEY
