name: Upload website affordable

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@master


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      
      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build


      - name: Set up AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-2

          

      - name: Deploy to AWS S3
        run: |
          aws s3 sync build/ s3://flightroute/ --acl public-read --delete --debug
 
          
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

